server:
  port: 8080

# Spring配置
spring:
  profiles:
    active: druid
  cache:
    ehcache:
      config: classpath:ehcache.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql