server:
  port: 8080

# Spring配置
spring:
  profiles:
    active: druid


# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zhlab.demo.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql