server:
  port: 8080

# Spring配置
spring:
  profiles:
    active: druid
  cache:
    ehcache:
      config: classpath:ehcache.xml
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql