server:
  port: 8004

spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: iamzhangx
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
